version: "3"

services:
  app:
    image: maykonmorais/app
    build:
      context: ./app
    container_name: app
    networks:
      - node-net
    ports:
      - "80:80"

  backend:
    image: maykonmorais/backend
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    networks:
      - node-net
    ports:
      - "3000:3000"

networks:
  node-net:
    driver: bridge
